# Generated by Django 3.2.5 on 2021-08-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsqr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='http_status',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.SmallIntegerField(choices=[(1, 'NOT_STARTED'), (2, 'PENDING'), (3, 'FINISHED')], default=1),
        ),
    ]
